# -- Number of replicas
replicaCount: 1

image:
  repository: ubuntu/bind9
  tag: latest
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalTrafficPolicy: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: LoadBalancer

# -- Resource limits and requests
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# -- Persistent volume for BIND cache data
persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce

# -- NetworkPolicy for DNS traffic (TCP/UDP 53)
networkPolicy:
  enabled: false

# -- Config files to mount from named.conf ConfigMap
# -- These are always mounted at /etc/bind/
namedConfig:
  options: |
    options {
      directory "/var/cache/bind";
      listen-on port 53 { any; };
      listen-on-v6 { any; };
      allow-recursion { any; };
      notify yes;
      dnssec-validation auto;
    };
  logging: |
    logging {
      channel query_logging {
        file "/var/cache/bind/named_querylog" versions 10 size 100M;
        print-time yes;
        severity debug 1;
      };
      category queries { query_logging; };
      channel syslog_errors {
        syslog user;
        severity error;
      };
      category default { syslog_errors; };
      category lame-servers { null; };
    };
  acls: []
  keys: |
    key "rndc-key" {
            algorithm hmac-md5;
            secret "aFqbAr+2u4ON3e/ZsJRr7fNqXZpXiP0+mHMVqnu0twk=";
    };

# -- Zone definitions and their file contents
zones:
  # Root hints
  - name: root.hint
    path: "."
    type: hint
    file: /etc/bind/zones/root.hint
  # Localhost
  - name: localhost
    path: localhost
    type: master
    file: /etc/bind/zones/localhost
  # Reverse localhost
  - name: 127.0.0
    path: 0.0.127.in-addr.arpa
    type: master
    file: /etc/bind/zones/127.0.0
# -- Extra options to add to named.conf
extraIncludes: []
#  - /etc/bind/named.conf.local
