{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bind9.fullname" . }}
  labels: {{- include "bind9.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "bind9.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
  egress:
    - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
{{- end }}
